apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wtr6ed0wo-nodejs
  janus-idp.io/tekton: wtr6ed0wo-nodejs
  backstage.io/kubernetes-id: wtr6ed0wo-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wtr6ed0wo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
